language: cpp

compiler:
  - gcc
  - clang

env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release
  - CMAKE_BUILD_TYPE=Debug GCC_5_1=ON
  - CMAKE_BUILD_TYPE=Release GCC_5_1=ON

matrix:
  exclude:
    - compiler: clang
      env: CMAKE_BUILD_TYPE=Debug GCC_5_1=ON
    - compiler: clang
      env: CMAKE_BUILD_TYPE=Release GCC_5_1=ON

before_install:
  # CMake 3.x
  - sudo dpkg -r cmake cmake-data
  - sudo add-apt-repository -y ppa:dcthomp/smtk

  # gcc-4.9
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # clang 3.4
  - if [ "$CC" == "clang" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  # CMake and ninja
  - sudo apt-get install ninja-build cmake
  - cmake --version
  - ninja --version

  # g++, for Clang we use g++-4.9 since we need a newer version of libstc++
  - if [ "$GCC_5_1" == "ON" ]; then
      sudo apt-get install -qq g++-5;
    else
      sudo apt-get install -qq g++-4.9;
    fi

  # Also use it if that's what we're going for
  - if [ "$CC" == "gcc" ]; then
      if [ "$GCC_5_1" == "ON" ]; then
        export CC=gcc-5 &&
        export CXX="g++-5";
      else
        export CC=gcc-4.9 &&
        export CXX="g++-4.9";
      fi
    fi

  # clang 3.4
  - if [ "$CC" == "clang" ]; then
      sudo apt-get install --allow-unauthenticated -qq clang-3.4 &&
      export CC=clang-3.4 &&
      export CXX=clang++-3.4;
    fi

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DRC_ENABLE_TESTS=ON -DRC_ENABLE_EXAMPLES=ON -DRC_ENABLE_GMOCK=ON -DRC_ENABLE_BOOST=ON -G Ninja ..
  - ninja -j1 # Don't run out of memory, please
  - ctest --output-on-failure